zero-to-mastery/Halloween-Hacktoberfest-Edition

contributors.md
facts.txt
index.html
names.html
names.js
names.txt

Added the Hallowen Name section

Name section

---

contributors.md
index.html

Changed some text and added my name to contributors.

Halloween Recipes

---

contributors.md
css/style.css
index.html

Alignment Of h1

---

css/style.css
index.html

i changed the position of content in slider 2 and slider 3

Changed Position

---

contributors.md
designs.html
facts.html
index.html
names.html
recipes.html

Fixed some typos and enabled the links to the pumpkin design webpage as well as adding in a template design page.

Added Pumpkin Design template page

---

js/movieSearch.js
movieSearch.html

Just the beginning of it, but will add more later.

added super sneaky movieSearch page — movieSearch.html

---

contributors.md
js/names.js
names.html

Update and simplify names.js + names.html for improvement to halloween name meanings. Replace broken script links with CDN paths. Add name to Contributors.

Updates / improvements to Halloween name meanings

---

css/style.css
index.html

Added color to home page active nav link with inline style.

 fixed active link color

---

contributors.md
css/carousel.css
css/style.css
index.html

Hello. I updated a little bit of mobile responsive design. 
Add media query and put myself on the contributors list.
Please let me know if there is any issue.

updated mobile responsive design

---

css/carousel.css
css/style.css

I COMMENTED OUT THE NAVBAR COLOUR AS IT OVERRIDES THE TRANSPARENCY ON THE HOME PAGE. 
CAN ANYONE MAKE IT SO THAT IT CATCHES COLOUR AS WE SCROLL DOWN THE PAGE?

adding the body padding of 100px and carousel padding of -100px;

---

css/style.css
js/index.js

Added css class and javascript functionality to make navbar background requested color on scroll. Color does not show when navbar is at the top of the page.

Navbar Color on Scroll

---

css/style.css

Made link colors orange instead of blue as requested in issue #69.

Footer text color

---

names.txt

adding 'all' so the sentence is more clear.

grammar fix

---

names.html

fixed issue with name generator

added missing script link

---

js/headFoot.js

@MattCSmith Please check if this method is suitable or not.

 fixing base url active link

---

css/facts.css
facts.html

fixed position of footer in facts

fixed footer

---

css/books.css
css/movies.css
css/style.css
halloweenBooks.html
halloweenMovies.html

- alphabetized movie entries
- updated styling of movie lists
- made movie and book links open in new tabs 
- added books to list of spooky reads

Style and content updates

---

README.md
designs.html

Image width was improper so fixed it by making it same as for all
Also readme.md file is updated with grammar

Corrected grammar and resolved image(pumkin5)

---

designs.html
facts.html
halloweenBooks.html
recipes.html

Jquery and bootstrap script needed to be on the html pages for navigation collapse to work.

fixed mobile navigation issue for designs, facts, books, recipes pages

---

facts.html

Three changes: added a new font to the button, reduced the font size and reduced the padding! My first commit 🙌

Changes to button text, size and padding

---

css/facts.css
facts.html
halloweenBooks.html
index.html

changed fonts and some positioning

updated facts.html

---

css/books.css
css/carousel.css
css/movies.css
halloweenBooks.html
halloweenMovies.html

Hello. I just updated some css.
1. Books page // footer css. Fixed it to the bottom. It was floating in the middle of the page.
2. Movies page // carousel css. Each images had different sizes, so i made it fit to the screen.
Please let me know if there is any issue.

PR from Wooz

---

css/style.css
index.html

#87
-> implemented AOS 
-> applie AOS to landing page elements

implemented AOS and applied to elements

---

index.html

Removed Placeholder text to be a fact form the facts.txt

added content for the banner section

---

facts.html

added halloween facts

---

contributors.md
css/fog.css
designs.html
facts.html
halloweenBooks.html
halloweenMovies.html
index.html
movieSearch.html
names.html
recipes.html

This works okay and just in general is pretty nifty. I think the only way to get away from that jarring load deal is to not load stuff via that method OR put in a master rule which pushes the content below the fold while the fog remains and let it setup behind the layer the fog is filling.

Added fog and fog effect to each slide in an attempt to hide the CSS load

---

js/facts.js
js/movieList.js

Hello, I updated some of the functions to arrow functions and changed "var" to let/const.
Hope I didn't break anything ;(.

Updating JS

---

contributors.md
css/movies.css
css/style.css
halloweenMovies.html
js/movieList.js

some optical improvments for the halloweenMovies page:
- text center in random movies div + adding two columns
----------------------------------------------------------------------------------
add myself to the contributors.md

some optical improvments for the halloweenMovies page

---

css/facts.css
facts.html

1) Removed inline styles for the fact button and added class "btn and btn-primary" to be consistent with all other pages
2) added an .btn-fact class in the facts.css file to further improve styling for the specific fact button
3) added inline style (text-align: center ) to outer card-body container to allow the button to be centered on the page

fixed the styling for the fact button

---

costumes.html
css/costumes.css
js/headFoot.js

adding costumes.html and costumes.css and editing headFoot.js

adding a halloween costumes section

---

contributors.md

Just added my name to the list of contributors

New contributor

---

facts.txt

facts added

---

costumes.html
js/headFoot.js

resolved a number of issues with unused/needed files & added some conditional checks for null

loading issues & null conditionals

---

css/style.css

fix navbar alignment

---

css/catchTheWitch.css

fix score margin

---

contributors.md

add name to contributors

---

contributors.md

I added myself to the list for this project. This is my first open-source project, and I'm excited to contribute!

test for contributiion

---

contributors.md

I had a made a PR in the past, I guess PR#125.

had not added my name to the contributors list

---

contributors.md
halloweenBooks.html
js/movieList.js

bronasek added some content

---

index.html

Fixes the "read more" links not having the same style as the rest of the buttons on the index page. Should solve issue #169.

Uniform button styles on index page

---

css/fog.css

Trying  MattCSmith's suggestion for bug https://github.com/zero-to-mastery/Halloween-Hacktoberfest/issues/165

Trying  MattCSmith's suggestion for bug

---

about.html
css/about.css
js/headFoot.js

I am adding a new page i.e About.html

Adding About

---

halloweenBooks.html

Add Henry James' The Turn of the Screw to book list.

Add to book list

---

js/movieList.js

Just added "The Texas Chainsaw Massacre" to the existing movie list.

Added new movie to list

---

css/books.css
halloweenBooks.html

Just Aligned images in a better way , What do you guys think of it ?

Books Arrangement

---

css/pumpkinDesigns.css
designs.html

Put images into Bootstrap columns and cards. Should be responsive and images all the same height.

Pumpkin Design Cards

---

contributors.md

Adding name to contributors

---

designs.html

Fixed a little error on the design page causing image not to display. Please check it out.

fixed an image not displaying on the design page

---

css/carousel.css
designs.html
halloweenMovies.html
js/movieList.js

The home page slider text can be hard to read, so I have added a slight overlay to the carousel element.
I found some script errors and duplicated code on the movie list page and that is addressed in this PR.

Readability and functionality improvements for home and movie list

---

halloweenGames.html

Added "F.E.A.R." to list of video games.

Added new game

---

about.html
css/about.css
recipes.html

- add margin to image to look cleaner
- margin for headers to make them more outstanding

improve about page

---

css/pumpkinDesigns.css
designs.html

I didn't add any images, but there are some handy directions on how to carve a pumpkin as well as a link to the recipes page (still need to add a recipe there for pumpkin muffins) and a small change to the header font in the css file for pumpkin design.

added section for how to carve a pumpkin to the pumpkin design page

---

css/fog.css
halloweenGames.html

Added more games and fit fog to bottom of page

added more games

---

js/movieList.js

Added all three Hotel Transylvania movies to the list of movies, great for the whole family.

adding a couple more family friendly movies to the list.

---

js/facts.js

Fixed the Facts page button from Issue #205

fix: Facts page button

---

css/pumpkinDesigns.css
designs.html

old search bar was looking bad at grey shade i changed it with expandable seachbox . Have look

search bar change from simple to expandable

---

css/about.css
css/pumpkinDesigns.css

There was unwanted height in about page i removed it and some minor css changes for fine rendering.

About - Unwanted Height removed and smoothness added in css

---

css/about.css
css/facts.css
css/movies.css
css/recipes.css
css/style.css
facts.html
js/movieList.js
recipes.html

In Fact page removed unwanted height and some minor css changes.
In Movies page title of movies are shown in very proper manner old one was not aligned .

Changes done in Facts and Movies pages.

---

activities.html
catchTheWitch.html
costumes.html
css/catchTheWitch.css
css/fog.css
css/style.css
facts.html
names.html

I have changed footer's height and I'm fixing footers that are not on the bottom of the page. Also, I did some QOL changes here and there.

Fixing footer not sticking to the bottom

---

css/style.css

- Fixed navbar's animation introduced in #224 
- Added back --navbar-height and changed it to 12vh to look better
- Fixed some indentation in style.css

Fixed navbar animation and added back navbar-height

---

js/headFoot.js

Finally refactoring headFoot.js
Deleting empty index.js

Refactoring headFoot.js

---

css/activities.css

Adds "+" and "-" to accordion buttons

---

js/names.js

Played around with names.js until the 'new name' button was working properly. Since Chrome would not allow me to do the XMLHttpRequest to a url starting with file://, made a variable that was simply the text file names.txt. Would like to see this merged and then can see if the XMLHttpRequest works or if more work needs to be done on the js file.

(attempt at) Fixing the  'new name' button

---

js/names.js

This should fix the new name button, I had forgotten to uncomment the function call for reading the txt file during my debugging.

forgot to uncomment function call for names.txt file to be read

---

.gitignore
backgrounds.html
contributors.md
css/backgrounds.css
js/headFoot.js

Hello 
I just add a new section and i called it backgrounds hopefully it will be good contribution . 
can you please review it .  
thank you

Background

---

costumes.html

Added Darth Vader to costumes.

add-costume

---

css/carousel.css
css/style.css

- Stop header from shrinking too much
- Make sure slider isn't below everything so you can click arrows to navigate

Slider and Header CSS sleanup

---

css/style.css

use correct styling to center navigation items.

centered nav items

---

css/carousel.css

the carousel now shows inline with the navbar rather than behind.

added margin to carousel

---

js/movieList.js
js/movieSearch.js

Movies section

---

css/about.css

converted em to rem. keeping consistent with root element size when the page size changes

Changed 'em' to 'rem'

---

html/index.html

Made button attributes changes in index.html to style Read More button

Style Read More button in index page - issue #169

---

contributors.md
css/books.css
css/pumpkinDesigns.css
html/books.html
html/designs.html

-add scrollbars for pages that have a search button (designs and books)
-add name to contributors

adding scrollbars for designs and books pages

---

css/halloweenGames.css
html/games.html
js/gameSearch.js

-also deleted fog-roll height from halloweenGames.css in order to activate scroll bar in games list

Add scrollbars

---

css/books.css
html/books.html

Fixed sticked footer to books container. Now it is at the bottom as it should and section looks better. I also removed second container class, because it is unnecessery.

fixed books section

---

images/icons/bat.svg
images/icons/candle.svg
images/icons/frankenstein.svg
images/icons/ghost.svg
js/canvas.js

adding Halloween icons to the canvas (Background section)

---

index.html

removed untagged "div" that showed as text

removed untagged "div" that showed as text.

---

index.html
js/movieList.js

Formatted enable sound and mute sound buttons on bottom of home page, and fixed typo in movie list

added styling to sound buttons on bottom of home page

---

contributors.md

Added myself to the list, please let me join :D

just adding my name to contributor

---

contributors.md
css/about.css

Change picture style on hover in about page.

Change picture style on hover

---

html/recipes.html

the picture did not load on the website.
I added a new one which matches with the dish.

fixed picture issue

---

contributors.md

Hello, this is my first contribution and I just added my name to contributors list, so can you let me in? Thanks :)

Adding my name to contributors list :)

---

css/recipes.css
html/recipes.html

Hi, I changed the font and color on recipe page, please merge it, thanks!

style change recipe

---

html/recipes.html

I have fixed the recipes text and now it looks better.

Changes made

---

index.html

Some spelling, punctuation and grammar mistakes corrected. :)

Spelling and punctuation fix

---

contributors.md

Add my name to list of contributors, please.

Update contributors list

---

css/movies.css
html/books.html
html/movies.html
js/movieList.js

I added a searchbar in the movie page!

added searchbar in movie page

---

html/backgrounds.html
html/costumes.html

Fixed some missing div tags in the HTML files **costumes.html** and **backgrounds.html** .
Without these div tags when going to reduced size, the Hamburger button it's not working (not running the necessary JQuery and Bootstraps scripts).

fixing footer div for scripts

---

css/movies.css
html/movies.html
js/movieList.js

modified search functions and added scroll bar in movie page.

added scroll in movie page

---

html/books.html

Added a new book.
Happy Halloween to everybody!

Book: Ink and Bone

---

html/backgrounds.html
html/costumes.html
js/movieList.js

adding another movie to JS file **movieList.js**

Adding a movie

---

html/activities.html

Shouldn't could also have been "ought not", but I thought it sounded more natural this way.

fixed a few spelling and grammar mistakes

---

html/facts.html

Hey, I just added another fact about Halloween.

Added fact about candies
